
# Git Aliases
alias gs='git status'
alias gcm='git commit -m'
alias gcma='git commit -A -m'
alias gl='git log'
alias ga='git add -A'
alias gb='git branch'
alias gco='git checkout'
alias gf='git fetch'
alias gst='git stash'
alias gp='git push origin'
alias gpl='git pull origin'
alias gundo='git reset --soft HEAD^; git reset HEAD'
alias master='git checkout master'
alias dev='git checkout dev'
alias qa='git checkout qa'

# Git Nav Aliases
alias downloads='cl ~/Downloads'
alias documents='cl ~/Documents'
alias gogit='cl ~/git'
alias gg='gogit'

alias gowestsidemuaythai='cd ~/git && cl westside-muaythai'
alias gowestside='gowestsidemuaythai'
alias gowest='gowestsidemuaythai'

alias gozhanglingphotography='cd ~/git && cl zhanglingphotography'
alias gozhang='gozhanglingphotography'
alias goling='gozhanglingphotography'

alias gonangs='cd ~/git && cl nangs-homemade'
alias gonang='gonangs'
alias gohomemade='gonangs'

# Work Git Aliases
alias goveem='gogit && cd veem'
alias gowork='goveem'
alias veem='goveem'
alias gostatecomponents='cl state-components'
alias statecomponents='gostatecomponents'
alias gosc='gostatecomponents'
alias sc='gostatecomponents'

alias customerfrontend='veem && cl customer-fe-app && nvm use'
alias cfe='customerfrontend'
alias gocfe='customerfrontend'
alias gocustomerfrontend='customerfrontend'
alias gofe='customerfrontend'
alias fe='customerfrontend'
alias gocustfrontendstatecomponents='customerfrontend && statecomponents'
alias gocfesc='gocustfrontendstatecomponents'
alias gocfes='gocustfrontendstatecomponents'
alias gofes='gocustfrontendstatecomponents'
alias fesc='gocustfrontendstatecomponents'
alias fes='gocustfrontendstatecomponents'
alias cfes='gocustfrontendstatecomponents'
alias cfesc='gocustfrontendstatecomponents'


alias adminfrontend='veem && cl admin-fe-app && nvm use'
alias afe='adminfrontend'
alias goafe='adminfrontend'
alias goadminfrontend='adminfrontend'
alias goadminfrontendstatecomponents='adminfrontend && gostatecomponents'
alias goafesc='goadminfrontendstatecomponents'
alias goafes='goadminfrontendstatecomponents'
alias afes='goadminfrontendstatecomponents'
alias afesc='goadminfrontendstatecomponents'

alias embedwidgets='veem && cl embed-widgets && nvm use'
alias ew='embedwidgets'
alias embed='embedwidgets'
alias goembed='embedwidgets'
alias goembedwidgets='embedwidgets'
alias goembedwidgetsstatecomponents='embedwidgets && gostatecomponents'
alias goewsc='goembedwidgetsstatecomponents'
alias goaews='goembedwidgetsstatecomponents'
alias ews='goembedwidgetsstatecomponents'
alias ewsc='goembedwidgetsstatecomponents'
alias es='goembedwidgetsstatecomponents'
alias esc='goembedwidgetsstatecomponents'


# Profile Alias
alias sourceprofile='source ~/.bash_profile'
alias sourcep='sourceprofile'
alias sourcebash='sourceprofile'
alias sourceb='sourceprofile'

# Edit profile
alias codeprofile='code ~/.bash_profile'
alias editprofile='codeprofile'
alias codep='codeprofile'
alias editp='codeprofile'
alias codebash='codeprofile'
alias editbash='codeprofile'
alias codeb='codeprofile'
alias editb='codeprofile'
# Edit alias
alias codealias='code ~/.bash_aliases'
alias editalias='codealias'
alias codealiases='code ~/.bash_aliases'
alias editaliases='codealias'
alias codea='codealias'
alias edita='codealias'
# Edit functions
alias codefunctions='code ~/.bash_functions'
alias editfunctions='codefunctions'
alias codefunction='codefunctions'
alias editfunction='codefunctions'
alias codec='codefunctions'
alias editc='codefunctions'
alias editf='codefunctions'
# Edit Veem
alias editveem='code ~/.veem_profile'
alias editv='editveem'
alias codeveem='editveem'
alias codev='editveem'

# ZSH
alias sourcezsh='source ~/.zshrc'
alias sourcez='sourcezsh'

alias codezsh='code ~/.zshrc'
alias editzsh='codezsh'
alias codez='codezsh'
alias editz='codezsh'